---
- name: Configure termux
  hosts: termux
  vars:
    ansible_remote_tmp: /data/data/com.termux/files/home/.ansible/tmp
  tasks:
    - name: Debug variables
      ansible.builtin.debug:
        var: ansible_facts
    - name: Update all packages
      tags: apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: Install all packages
      tags: apt
      ansible.builtin.apt:
        name:
          # AI
          - aichat
          # anime
          - ani-cli
          # book
          - bk
          # chat
          - weechat
          # dev
          - direnv
          - editorconfig-core-c-static
          - editorconfig-core-c
          - just
          - make
          - termux-apt-repo
          - termux-create-package
          # sqlite
          - sqlite
          # nodejs
          - nodejs-lts
          # rust
          - rust
          # markdown
          - marksman
          # json
          - jq
          # go
          - golang
          # haskell
          - ghc
          # toml
          - taplo
          # latex
          - tectonic
          - texlab
          - texlive-bin
          # python
          - python
          # document
          - pandoc
          - texinfo
          # download
          - aria2
          - axel
          - cloneit
          - python-yt-dlp
          - transmission
          # database
          - recutils
          # editor
          - helix
          - helix-grammars
          - neovim
          - python-pynvim
          - vim
          - kakoune
          - kakoune-lsp
          - emacs
          # encrypt
          - gopass
          # image
          - gnuplot
          # image edit
          - imagemagick
          # math
          - qalc
          # ascii art
          - figlet
          - toilet
          # dotfiles
          - chezmoi
          # file manage
          - lf
          - clifm
          - nnn
          - ranger
          - vifm
          - yazi
          - mc
          # git
          - gh
          - git
          # git stats
          - onefetch
          # git tui
          - gitui
          - lazygit
          - tig
          # git diff
          - diff-so-fancy
          - git-delta
          # git encrypt
          - git-crypt
          # git script
          - git-extras
          # git lfs
          - git-lfs
          # translation
          - translate-shell
          # typing
          - ttyper
          # share
          - croc
          - dufs
          - miniserve
          - rclone
          - ttyd
          # shell
          - fish
          # which
          - which
          # screen
          - tmux
          - zellij
          # cd
          - zoxide
          # man
          - tealdeer
          # prompt
          - starship
          - oh-my-posh
          # cp
          - rsync
          # rename
          - rnr
          # snippets
          - navi
          - pet
          # grep
          - ripgrep
          # fuzzy
          - broot
          - fzf
          # completion
          - carapace
          # history
          - atuin
          - mcfly
          # paper
          - bat
          - moor
          # utils
          - moreutils
          # system
          - termux-api
          # package manager
          - oma
          - nala
          # network
          - iproute2
          # ping
          - gping
          # font
          - fontconfig-utils
          # dns
          - doge
          - q-dns-client
          # ls
          - eza
          - tree
          # stats
          - fastfetch
          - cpufetch
          # top
          - htop
          # find
          - fd
          # du
          - diskus
          - dua
          - duc
          - dust
          - gdu
          # df
          - duf
          # archive
          - atool
          - unrar
          # services
          - termux-services
          # ssh
          - openssh
          # rss
          - newsboat
          # video edit
          - ffmpeg
    - name: Create folder
      tags: cargo
      ansible.builtin.file:
        path: .cargo
        state: directory
        mode: "0755"
    - name: Set cargo config
      tags: cargo
      ansible.builtin.copy:
        content: |
          [source.crates-io]
          replace-with = 'mirror'

          [source.mirror]
          registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

          [registries.mirror]
          index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
        dest: .cargo/config.toml
        mode: "0600"
    # - name: Create folder
    #   tags: pip
    #   ansible.builtin.file:
    #     path: .pip
    #     state: directory
    #     mode: "0755"
    # - name: Set pip config
    #   tags: pip
    #   ansible.builtin.copy:
    #     content: |
    #       [global]
    #       index-url = https://mirrors.nju.edu.cn/pypi/web/simple/
    #       [install]
    #       trusted-host = mirrors.nju.edu.cn
    #     dest: .pip/pip.conf
    #     mode: "0600"
    - name: Install pip packaging
      tags: pip
      ansible.builtin.command: pip install packaging
    - name: Pip packages
      tags: pip
      ansible.builtin.pip:
        name:
          - pipx
    - name: Install pipx packages
      tags: pipx
      environment:
        ANDROID_API_LEVEL: 28
      community.general.pipx:
        name: "{{ item }}"
        executable: /data/data/com.termux/files/usr/bin/pipx
      loop:
        - copyparty
        - mdformat
        - advance-touch
