windows_pipx_packages:
  - advance-touch
  - xonsh[full]
  - mutagen
  - jedi-language-server
  - python-lsp-server
  - basedpyright
  - grip
  - names
  - leo
  - copyparty
  - ffmpeg-progress-yield
  - vim-vint
  - aria2p[tui]
  - tewi-torrent
  - tvnamer
  - mnamer
