---
- name: Install pipx packages
  tags: "{{ pipx_tags }}"
  environment:
    ANDROID_API_LEVEL: 28
  community.general.pipx:
    name: "{{ pipx_packages }}"
    executable: /data/data/com.termux/files/usr/bin/pipx
