windows_scoop_state: "present"
windows_scoop_packages: ""
windows_scoop_global: false
windows_scoop_reboot: false
windows_scoop_packages_main_AI:
  - main/aichat
windows_scoop_packages_main_android:
  - main/adb
  - main/scrcpy
windows_scoop_packages_main_audio:
  - main/mpd
  - main/navidrome
  - main/cliamp
windows_scoop_packages_main_backup:
  - main/restic
  - main/resticprofile
  - main/rdiff-backup
  - main/kage
windows_scoop_packages_main_CA:
  - main/cacert
windows_scoop_packages_main_CMS:
  - main/hugo
  - main/cobalt
windows_scoop_packages_main_dev:
  - main/chsrc
  - main/editorconfig
  - main/dprint
  - main/aspell
  - main/diffutils
  - main/wakatime-cli
windows_scoop_packages_main_bash:
  - main/shellcheck
  - main/shfmt
windows_scoop_packages_main_binary:
  - main/binutils
windows_scoop_packages_main_c:
  - main/clangd
windows_scoop_packages_main_csharp:
  - main/scriptcs
  - main/bflat
windows_scoop_packages_main_compile:
  - main/make
windows_scoop_packages_main_environment:
  - main/task
  - main/cmake
  - main/msys2
  - main/direnv
  - main/tree-sitter
  - main/dirhash
windows_scoop_packages_main_haskell:
  - main/haskell
  - main/haskell-cabal
  - main/haskell-language-server
  - main/stack
windows_scoop_packages_main_go:
  - main/go
windows_scoop_packages_main_json:
  - main/jq
windows_scoop_packages_main_latex:
  - main/texlab
  - main/tectonic
windows_scoop_packages_main_lua:
  - main/lua-language-server
  - main/stylua
windows_scoop_packages_main_markdown:
  - main/autocorrect
  - main/marksman
windows_scoop_packages_main_nodejs:
  - main/yarn
  - main/pnpm
windows_scoop_packages_main_perl:
  - main/perl
windows_scoop_packages_main_powershell:
  - main/powershelleditorservices
windows_scoop_packages_main_python:
  - main/ruff
  - main/ty
  - main/uv
windows_scoop_packages_main_rust:
  - main/rust
  - main/cargo-binstall
windows_scoop_packages_main_sql:
  - main/sqlite
windows_scoop_packages_main_toml:
  - main/taplo
  - main/tombi
windows_scoop_packages_main_web:
  - main/static-web-server
windows_scoop_packages_main_yaml:
  - main/yamlfmt
windows_scoop_packages_main_disk:
  - main/smartmontools
  - main/dd
windows_scoop_packages_main_document:
  - main/pandoc
  - main/cht
windows_scoop_packages_main_dotfile_manager:
  - main/chezmoi
windows_scoop_packages_main_downloader:
  - main/gallery-dl
  - main/yt-dlp
  - main/pget
  - main/wget2
  - main/wget
  - main/aria2
windows_scoop_packages_main_editor:
  - main/vim
  - main/helix
  - main/neovim
  - main/fresh
windows_scoop_packages_main_email:
  - main/mailsend
windows_scoop_packages_main_encrypt:
  - main/gpg
  - main/openssl
  - main/gopass
  - main/gopass-jsonapi
  - main/sops
windows_scoop_packages_main_file_manager:
  - main/lf
  - main/yazi
  - main/superfile
windows_scoop_packages_main_fuzzy_finder:
  - main/broot
  - main/fzf
windows_scoop_packages_main_git:
  - main/jj
windows_scoop_packages_main_git_auto:
  - main/gitomatic
windows_scoop_packages_main_git_bug:
  - main/git-bug
windows_scoop_packages_main_git_github:
  - main/gh
windows_scoop_packages_main_git_push:
  - main/mob
  - main/legit
windows_scoop_packages_main_git_lfs:
  - main/git-lfs
windows_scoop_packages_main_git_fixup:
  - main/git-absorb
windows_scoop_packages_main_git_diff:
  - main/diff-so-fancy
  - main/delta
  - main/difftastic
windows_scoop_packages_main_git_encrypt:
  - main/git-crypt
windows_scoop_packages_main_git_tui:
  - main/gitui
windows_scoop_packages_main_git_gui:
  - extras/git-cola
windows_scoop_packages_main_git_server:
  - main/gogs
windows_scoop_packages_main_git_search:
  - main/gitql
windows_scoop_packages_main_git_hook:
  - main/lefthook
windows_scoop_packages_main_image:
  - main/gnuplot
windows_scoop_packages_main_image_info:
  - main/exiftool
windows_scoop_packages_main_image_edit:
  - main/imagemagick
windows_scoop_packages_main_network:
  - main/dog
  - main/nali
  - main/nmap
  - main/q-dns
  - main/tcping
windows_scoop_packages_main_proxy:
  - main/connect
windows_scoop_packages_main_scoop_helper:
  - main/scoop-search
windows_scoop_packages_main_search:
  - main/everything-cli
windows_scoop_packages_main_remote:
  - main/termscp
  - main/ttyd
windows_scoop_packages_main_qr_code:
  - main/qr
  - main/qrcp
windows_scoop_packages_main_share:
  - main/croc
  - main/cwrsync
  - main/dufs
  - main/miniserve
  - main/portal
  - main/rclone
  - main/syncthing
  - main/alist
  - main/serve
  - main/simple-http-server
  - main/git-annex
windows_scoop_packages_main_shell:
  - main/clink
  - main/clink-completions
  - main/cmder-full
  - main/pwsh
  - main/nu
  - main/yori
windows_scoop_packages_main_ascii_art:
  - main/rainbow
windows_scoop_packages_main_cd:
  - main/zoxide
windows_scoop_packages_main_df:
  - main/duf
windows_scoop_packages_main_du:
  - main/dua
  - main/dust
windows_scoop_packages_main_find:
  - main/fd
windows_scoop_packages_main_grep:
  - main/grep
  - main/ripgrep
  - main/gawk
  - main/igrep
windows_scoop_packages_main_history:
  - main/mcfly
  - main/atuin
windows_scoop_packages_main_less:
  - main/bat
  - main/less
windows_scoop_packages_main_ls:
  - main/eza
windows_scoop_packages_main_man:
  - main/tealdeer
windows_scoop_packages_main_prompt:
  - main/starship
  - main/oh-my-posh
windows_scoop_packages_main_rename:
  - main/rnr
windows_scoop_packages_main_sed:
  - main/sd
  - main/sed
windows_scoop_packages_main_shasum:
  - main/shasum
windows_scoop_packages_main_snippets:
  - main/navi
windows_scoop_packages_main_system_info:
  - main/fastfetch
  - main/ntop
  - main/btop
  - main/bottom
  - main/cpufetch
windows_scoop_packages_main_tmux:
  - main/psmux
  - main/zellij
windows_scoop_packages_main_typing:
  - main/ttyper
windows_scoop_packages_main_unrar:
  - main/unrar
  - main/unzip
windows_scoop_packages_main_utils:
  - main/coreutils
  - main/nircmd
windows_scoop_packages_main_mv:
  - main/brename
windows_scoop_packages_main_which:
  - main/which
windows_scoop_packages_main_system:
  - main/dos2unix
  - main/goodbyedpi
  - main/file
  - main/cyme
windows_scoop_packages_main_archive:
  - main/zip
  - main/bzip2
windows_scoop_packages_main_unpack:
  - main/innounp
  - main/gzip
  - main/innoextract
  - main/xz
windows_scoop_packages_main_sudo:
  - main/gsudo
windows_scoop_packages_main_service:
  - main/nssm
windows_scoop_packages_main_package_manager:
  - main/pipx
  - main/winget
  - main/topgrade
  - main/meta-package-manager
windows_scoop_packages_main_clipboard:
  - main/clipboard@0.9.0.1
windows_scoop_packages_main_notification:
  - main/noti
  - main/gotify-server
  - main/gotify-cli
windows_scoop_packages_main_ps:
  - main/witr
windows_scoop_packages_main_rm:
  - main/trashy
windows_scoop_packages_main_text_expander:
  - main/espanso
windows_scoop_packages_main_video_editor:
  - main/ffmpeg
  - main/butterflow
windows_scoop_packages_main_all: >-
  {{
    windows_scoop_packages_main_AI
    + windows_scoop_packages_main_android
    + windows_scoop_packages_main_audio
    + windows_scoop_packages_main_backup
    + windows_scoop_packages_main_CA
    + windows_scoop_packages_main_CMS
    + windows_scoop_packages_main_dev
    + windows_scoop_packages_main_bash
    + windows_scoop_packages_main_binary
    + windows_scoop_packages_main_c
    + windows_scoop_packages_main_csharp
    + windows_scoop_packages_main_compile
    + windows_scoop_packages_main_environment
    + windows_scoop_packages_main_haskell
    + windows_scoop_packages_main_go
    + windows_scoop_packages_main_json
    + windows_scoop_packages_main_latex
    + windows_scoop_packages_main_lua
    + windows_scoop_packages_main_markdown
    + windows_scoop_packages_main_nodejs
    + windows_scoop_packages_main_perl
    + windows_scoop_packages_main_powershell
    + windows_scoop_packages_main_python
    + windows_scoop_packages_main_rust
    + windows_scoop_packages_main_sql
    + windows_scoop_packages_main_toml
    + windows_scoop_packages_main_web
    + windows_scoop_packages_main_yaml
    + windows_scoop_packages_main_disk
    + windows_scoop_packages_main_document
    + windows_scoop_packages_main_dotfile_manager
    + windows_scoop_packages_main_downloader
    + windows_scoop_packages_main_editor
    + windows_scoop_packages_main_email
    + windows_scoop_packages_main_encrypt
    + windows_scoop_packages_main_file_manager
    + windows_scoop_packages_main_fuzzy_finder
    + windows_scoop_packages_main_git
    + windows_scoop_packages_main_git_auto
    + windows_scoop_packages_main_git_bug
    + windows_scoop_packages_main_git_github
    + windows_scoop_packages_main_git_push
    + windows_scoop_packages_main_git_lfs
    + windows_scoop_packages_main_git_fixup
    + windows_scoop_packages_main_git_diff
    + windows_scoop_packages_main_git_encrypt
    + windows_scoop_packages_main_git_tui
    + windows_scoop_packages_main_git_gui
    + windows_scoop_packages_main_git_server
    + windows_scoop_packages_main_git_search
    + windows_scoop_packages_main_git_hook
    + windows_scoop_packages_main_image
    + windows_scoop_packages_main_image_info
    + windows_scoop_packages_main_image_edit
    + windows_scoop_packages_main_network
    + windows_scoop_packages_main_proxy
    + windows_scoop_packages_main_scoop_helper
    + windows_scoop_packages_main_search
    + windows_scoop_packages_main_remote
    + windows_scoop_packages_main_qr_code
    + windows_scoop_packages_main_share
    + windows_scoop_packages_main_shell
    + windows_scoop_packages_main_ascii_art
    + windows_scoop_packages_main_cd
    + windows_scoop_packages_main_df
    + windows_scoop_packages_main_du
    + windows_scoop_packages_main_find
    + windows_scoop_packages_main_grep
    + windows_scoop_packages_main_history
    + windows_scoop_packages_main_less
    + windows_scoop_packages_main_ls
    + windows_scoop_packages_main_man
    + windows_scoop_packages_main_prompt
    + windows_scoop_packages_main_rename
    + windows_scoop_packages_main_sed
    + windows_scoop_packages_main_shasum
    + windows_scoop_packages_main_snippets
    + windows_scoop_packages_main_system_info
    + windows_scoop_packages_main_tmux
    + windows_scoop_packages_main_typing
    + windows_scoop_packages_main_unrar
    + windows_scoop_packages_main_utils
    + windows_scoop_packages_main_mv
    + windows_scoop_packages_main_which
    + windows_scoop_packages_main_system
    + windows_scoop_packages_main_archive
    + windows_scoop_packages_main_unpack
    + windows_scoop_packages_main_sudo
    + windows_scoop_packages_main_service
    + windows_scoop_packages_main_package_manager
    + windows_scoop_packages_main_clipboard
    + windows_scoop_packages_main_notification
    + windows_scoop_packages_main_ps
    + windows_scoop_packages_main_rm
    + windows_scoop_packages_main_text_expander
    + windows_scoop_packages_main_video_editor
  }}
windows_scoop_packages_extras_android:
  - extras/kdeconnect
  - extras/apkeep
windows_scoop_packages_extras_anime:
  - extras/filebot
windows_scoop_packages_extras_audio:
  - extras/ab-av1
  - extras/mplayer
  - extras/musikcube
windows_scoop_packages_extras_mpd:
  - extras/mpc
  - extras/ncmpc
windows_scoop_packages_extras_automation:
  - extras/autohotkey
  - extras/autoclicker
windows_scoop_packages_extras_browser:
  - extras/firefox
  - extras/brave
  - extras/qutebrowser
  - extras/ungoogled-chromium
  - extras/librewolf
windows_scoop_packages_extras_book:
  - extras/kavita
windows_scoop_packages_extras_chat:
  - extras/telegram
windows_scoop_packages_extras_sql:
  - extras/beekeeper-studio
windows_scoop_packages_extras_document:
  - extras/sioyek
  - extras/sumatrapdf
  - extras/zeal
  - extras/libreoffice
  - extras/wpsoffice
windows_scoop_packages_extras_download:
  - extras/aria-ng-gui
  - extras/eget
  - extras/transmission
  - extras/transgui
  - extras/qbittorrent
windows_scoop_packages_extras_editor:
  - extras/notepadplusplus
  - extras/vscodium
  - extras/emacs
  - extras/zed
  - extras/flow-control
windows_scoop_packages_extras_lunarvim:
  - extras/lunarvim
  - main/gcc
windows_scoop_packages_extras_education:
  - extras/anki
windows_scoop_packages_extras_encrypt:
  - extras/cfssl
  - extras/age
  - extras/keepassxc
  - extras/win-gpg-agent
windows_scoop_packages_extras_file_manager:
  - extras/mc
  - extras/vifm
  - extras/doublecmd
  - extras/totalcommander
windows_scoop_packages_extras_game:
  - extras/locale-emulator
  - extras/ludusavi
  - extras/playnite
  - extras/sunshine
windows_scoop_packages_extras_dev:
  - extras/universal-ctags
  - extras/cloc
windows_scoop_packages_extras_git:
  - extras/lazygit
  - extras/gitu
  - extras/sourcegit
windows_scoop_packages_extras_diff:
  - extras/meld
windows_scoop_packages_extras_image_viewer:
  - extras/nomacs
  - extras/qview
  - extras/oculante
  - extras/fsviewer
  - extras/yacreader
windows_scoop_packages_extras_image_edit:
  - extras/gimp
  - extras/photodemon
  - extras/photoflare
windows_scoop_packages_extras_keyboard:
  - extras/qmk-toolbox
  - extras/vial
  - extras/kanata
  - extras/komokana
windows_scoop_packages_extras_math:
  - extras/qalculate
windows_scoop_packages_extras_network:
  - extras/fiddler
windows_scoop_packages_extras_note:
  - extras/siyuan-note
windows_scoop_packages_extras_qr_code:
  - extras/qrscan
windows_scoop_packages_extras_remote_control:
  - extras/rustdesk
  - extras/tightvnc
windows_scoop_packages_extras_screen_shot:
  - extras/flameshot
windows_scoop_packages_extras_fuzzy_finder:
  - extras/television
windows_scoop_packages_extras_completion:
  - extras/carapace-bin
windows_scoop_packages_extras_todo:
  - extras/ttdl
windows_scoop_packages_extras_scoop_helper:
  - extras/sfsu
windows_scoop_packages_extras_snippets:
  - extras/pet
windows_scoop_packages_extras_powershell_module:
  - extras/psfzf
  - extras/psreadline
windows_scoop_packages_extras_paper:
  - extras/moor
windows_scoop_packages_extras_utils:
  - extras/util-linux-ng
windows_scoop_packages_extras_system:
  - extras/winspy
  - extras/windhawk
  - extras/powertoys
windows_scoop_packages_extras_window_manager:
  - extras/glazewm
  - extras/zebar
  - extras/komorebi
  - extras/yasb
  - extras/whkd
windows_scoop_packages_extras_proxy:
  - extras/flclash
windows_scoop_packages_extras_disk:
  - extras/diskgenius
  - extras/crystaldiskinfo
  - extras/wiztree
  - extras/windirstat
windows_scoop_packages_extras_launcher:
  - extras/flow-launcher
windows_scoop_packages_extras_package_manager:
  - extras/unigetui
windows_scoop_packages_extras_dhcp:
  - extras/dhcp-server
windows_scoop_packages_extras_timer:
  - extras/hourglass
windows_scoop_packages_extras_clipboard:
  - extras/copyq
  - extras/ditto
windows_scoop_packages_extras_cleaner:
  - extras/bleachbit
windows_scoop_packages_extras_search:
  - extras/everything
windows_scoop_packages_extras_kvm:
  - extras/deskflow
windows_scoop_packages_extras_temperature:
  - extras/coretemp
windows_scoop_packages_extras_uninstall:
  - extras/bulk-crap-uninstaller
windows_scoop_packages_extras_window:
  - extras/altsnap
windows_scoop_packages_extras_terminal:
  - extras/windows-terminal
  - extras/alacritty
  - extras/wezterm
windows_scoop_packages_extras_translation:
  - extras/copytranslator
windows_scoop_packages_extras_usb_driver:
  - extras/rufus
  - extras/ventoy
windows_scoop_packages_extras_video:
  - extras/ani-cli
windows_scoop_packages_extras_video_player:
  - extras/jellyfin-mpv-shim
  - extras/vlc
  - extras/mpv
  - extras/fladder
  - extras/gridplayer
  - extras/webtorrent
windows_scoop_packages_extras_video_edit:
  - extras/handbrake
windows_scoop_packages_extras_whiteboard:
  - extras/openboard
windows_scoop_packages_extras_all: >-
{{
  windows_scoop_packages_extras_android
  + windows_scoop_packages_extras_anime
  + windows_scoop_packages_extras_audio
  + windows_scoop_packages_extras_mpd
  + windows_scoop_packages_extras_automation
  + windows_scoop_packages_extras_browser
  + windows_scoop_packages_extras_book
  + windows_scoop_packages_extras_chat
  + windows_scoop_packages_extras_sql
  + windows_scoop_packages_extras_document
  + windows_scoop_packages_extras_download
  + windows_scoop_packages_extras_editor
  + windows_scoop_packages_extras_lunarvim
  + windows_scoop_packages_extras_education
  + windows_scoop_packages_extras_encrypt
  + windows_scoop_packages_extras_file_manager
  + windows_scoop_packages_extras_game
  + windows_scoop_packages_extras_dev
  + windows_scoop_packages_extras_git
  + windows_scoop_packages_extras_diff
  + windows_scoop_packages_extras_image_viewer
  + windows_scoop_packages_extras_image_edit
  + windows_scoop_packages_extras_keyboard
  + windows_scoop_packages_extras_math
  + windows_scoop_packages_extras_network
  + windows_scoop_packages_extras_note
  + windows_scoop_packages_extras_qr_code
  + windows_scoop_packages_extras_remote_control
  + windows_scoop_packages_extras_screen_shot
  + windows_scoop_packages_extras_fuzzy_finder
  + windows_scoop_packages_extras_completion
  + windows_scoop_packages_extras_todo
  + windows_scoop_packages_extras_scoop_helper
  + windows_scoop_packages_extras_snippets
  + windows_scoop_packages_extras_powershell_module
  + windows_scoop_packages_extras_paper
  + windows_scoop_packages_extras_utils
  + windows_scoop_packages_extras_system
  + windows_scoop_packages_extras_window_manager
  + windows_scoop_packages_extras_proxy
  + windows_scoop_packages_extras_disk
  + windows_scoop_packages_extras_launcher
  + windows_scoop_packages_extras_package_manager
  + windows_scoop_packages_extras_dhcp
  + windows_scoop_packages_extras_timer
  + windows_scoop_packages_extras_clipboard
  + windows_scoop_packages_extras_cleaner
  + windows_scoop_packages_extras_search
  + windows_scoop_packages_extras_kvm
  + windows_scoop_packages_extras_temperature
  + windows_scoop_packages_extras_uninstall
  + windows_scoop_packages_extras_window
  + windows_scoop_packages_extras_terminal
  + windows_scoop_packages_extras_translation
  + windows_scoop_packages_extras_usb_driver
  + windows_scoop_packages_extras_video
  + windows_scoop_packages_extras_video_player
  + windows_scoop_packages_extras_video_edit
  + windows_scoop_packages_extras_whiteboard
}}
windows_scoop_packages_nerd_fonts:
  - nerd-fonts/Maple-Mono-NF-CN
  - nerd-fonts/NerdFontsSymbolsOnly
  - nerd-fonts/FiraCode-NF-Mono
  - nerd-fonts/Noto-CJK-Mega-OTC
  - nerd-fonts/IosevkaTerm-NF-Mono
  - nerd-fonts/SarasaGothic-ttc
windows_scoop_packages_all: >-
  {{
    windows_scoop_packages_main_all
    + windows_scoop_packages_extras_all
  }}
