FILES := $(basename $(wildcard playbooks/*.yml))
TARGETS := $(FILES:playbooks/%=%)
.PHONY: all ${TARGETS}
all: ${TARGETS}
${TARGETS}:
    {{ if lookPath "ansible-lint" -}}
    ansible-lint playbooks/$@.yml
    {{ end -}}
    ansible-playbook playbooks/$@.yml
