FILES := $(basename $(wildcard playbooks/*.yml))
TARGETS := $(FILES:playbooks/%=%)
.PHONY: all ${TARGETS}
all: ${TARGETS}
{{ $env_var := "" }}
{{ if eq .chezmoi.os "windows" -}}
{{ $env_var = "LC_ALL=C.UTF-8 ANSIBLE_CONFIG=ansible.cfg " }}
{{ end -}}
${TARGETS}:
	{{ if and (lookPath "ansible-lint") (not (eq .chezmoi.os "windows")) -}}
	ansible-lint playbooks/$@.yml
	{{ end -}}
	{{ $env_var }}ansible-playbook -i inventory/hosts.yml playbooks/$@.yml
