- name: Set hostname
  tags:
    - system
    - hostname
  ansible.windows.win_hostname:
    name: "{{ windows_hostname_name }}"
  register: res
- name: Reboot
  tags:
    - system
    - reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

