---
- name: Configure wsl arch
  hosts: all
  ignore_unreachable: true
  tasks:
    - name: Debug variables
      ansible.builtin.debug:
        var: ansible_facts
    - name: Set mirror
      ansible.builtin.copy:
        content: |
          Server = https://mirror.nju.edu.cn/archlinux/$repo/os/$arch
          Server = https://mirrors.cernet.edu.cn/archlinux/$repo/os/$arch
        dest: /etc/pacman.d/mirrorlist
        mode: "0644"
    - name: Update system
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: Install pacman packages
      community.general.pacman:
        name:
          # git
          - git
          - lazygit
          # editor
          - emacs
          - helix
          - gvim
          # download
          - curl
          - wget
          # dotfiles
          - chezmoi
          # video
          - pipewire
          - mpv
          # shell
          - fish
          # prompt
          - starship
          # system
          - xclip
          - openssh
          - dos2unix
          - unzip
          # fuzzy
          - fzf
          # ls
          - eza
          # cd
          - zoxide
          # less
          - bat
          # top
          - btop
          # stats
          - fastfetch
          # python
          - uv
          # nodesj
          - nodejs
          # ansible
          - ansible
