- name: Configure windows admin
  hosts: all
  remote_user: admin
  ignore_unreachable: true
  tags: admin
  roles:
    - role: windows_choco
      windows_choco_packages:
        - visualstudio2026-workload-vctools
        - weasel
        - winfsp # rclone
        - steam
        - epicgameslauncher
        - "{{ 'tailscale' if inventory_hostname == 'work' else omit }}"
        - directx
        - name: openssh
          allow_prerelease: true
          package_params: /SSHServerFeature
    - role: windows_install_wsl
      when: inventory_hostname == 'work'
    - role: windows_hide_user
      windows_hide_user_name: Admin
    - role: windows_user
      windows_user_name: User
      windows_user_groups:
        - Users
    - role: windows_user
      windows_user_name: Game
      windows_user_groups:
        - Users
        - Administrators
    - role: windows_service
      windows_service_name: ssh-agent
      windows_srevice_state: started
      windows_srevice_start_mode: auto
    - role: windows_service
      windows_service_name: wsearch
      windows_srevice_state: stopped
      windows_srevice_start_mode: disabled
    - role: windows_optimize_powershell
    - role: windows_developer_mode
- name: Configure windows user
  hosts: all
  remote_user: user
  ignore_unreachable: true
  tags: user
  pre_tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:
  roles:
    - role: windows_install_scoop
    - role: windows_scoop_update
    - role: windows_scoop
      windows_scoop_packages: "{{ windows_scoop_packages_main_all }}"
    - role: windows_scoop
      windows_scoop_packages:
        - nodejs-lts
        - vscode
- name: Configure windows admin
  hosts: all
  remote_user: admin
  ignore_unreachable: true
  tags: admin
  tasks:
    - name: Reboot
      ansible.windows.win_reboot:
- name: Configure windows user
  hosts: all
  remote_user: user
  ignore_unreachable: true
  tags: user
  roles:
    - role: windows_scoop
      windows_scoop_packages: "{{ windows_scoop_packages_extras_all }}"
    - role: windows_scoop
      windows_scoop_packages: "{{ windows_scoop_packages_nerd_fonts }}"
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: extras-cn
      windows_scoop_bucket_repo: https://github.com/Scoopforge/Extras-CN
    - role: windows_scoop
      windows_scoop_packages:
        - extras-cn/neteasemusic
        - extras-cn/goldendict-ng
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: ourgal_scoop-bucket
      windows_scoop_bucket_repo: https://github.com/ourgal/scoop-bucket
    - role: windows_scoop
      windows_scoop_packages:
        - ourgal_scoop-bucket/dockfmt
        - ourgal_scoop-bucket/mtranserver
        - ourgal_scoop-bucket/altrun
        - ourgal_scoop-bucket/mani
        - ourgal_scoop-bucket/mmv
        - ourgal_scoop-bucket/cargo-update
        - ourgal_scoop-bucket/runany
        - ourgal_scoop-bucket/git-credential-gopass
        - ourgal_scoop-bucket/dbgate
        - ourgal_scoop-bucket/helix-ghost
        - ourgal_scoop-bucket/emacs-lsp-booster
        - ourgal_scoop-bucket/keep-sorted
        - ourgal_scoop-bucket/pikpak
        - ourgal_scoop-bucket/fdroidcl
        - ourgal_scoop-bucket/gesturesign
        - ourgal_scoop-bucket/Github-Store
        - ourgal_scoop-bucket/torrserver
        - ourgal_scoop-bucket/sdcv
        - ourgal_scoop-bucket/dwag
        - ourgal_scoop-bucket/install-nothing
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: Rinkerbel_scooped
      windows_scoop_bucket_repo: https://github.com/Rinkerbel/scooped
    - role: windows_scoop
      windows_scoop_packages:
        - Rinkerbel_scooped/seanime-server
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: java
      windows_scoop_bucket_repo: https://gitee.com/scoop-installer/Java
    - role: windows_scoop
      windows_scoop_packages:
        - java/openjdk17
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: charm
      windows_scoop_bucket_repo: https://github.com/charmbracelet/scoop-bucket
    - role: windows_scoop
      windows_scoop_packages:
        - charm/crush
    - role: windows_pipx
    - role: windows_cargo
    - role: windows_npm
    - role: windows_env
- name: Configure windows game user
  hosts: all
  remote_user: game
  ignore_unreachable: true
  tags: game
  pre_tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:
  roles:
    - role: windows_install_scoop
      windows_install_scoop_is_admin: true
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: aki
      windows_scoop_bucket_repo: https://github.com/akirco/aki-apps
    - role: windows_scoop
      windows_scoop_packages:
        - aki/wegame
    - role: windows_scoop_bucket
      windows_scoop_bucket_name: aki
      windows_scoop_bucket_state: absent
- name: Configure windows admin
  hosts: all
  remote_user: admin
  ignore_unreachable: true
  tags: admin
  pre_tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:
  roles:
    - role: windows_firewall
    - role: windows_hostname
      windows_hostname_name: "{{ inventory_hostname if inventory_hostname is defined else 'nuc' }}"
    - role: windows_service
      windows_service_name: Everything
      windows_service_state: started
      windows_service_path: C:\Users\User\scoop\apps\everything\current\everything.exe
      windows_service_cmd: C:\Users\User\scoop\apps\everything\current\everything.exe -svc
    - role: windows_user_right
      windows_user_right_name: SeRemoteInteractiveLogonRight
      windows_user_right_users: User
