"{{{ options
" yank highlight plugin
packadd! hlyank

" comment plugin
packadd! comment

" editorconfig plugin
packadd! editorconfig

" file picker
import 'find.vim'

" leader key
let g:mapleader = ' '

" close other buffers
nnoremap <leader>bo <cmd>%bd\|e#\|bd#<CR>

" save all and exit
nnoremap ZX <cmd>xa!<cr>

nmap <Enter> :

" center line when searching
" nnoremap n nzzzv
" nnoremap N Nzzzv

" file picker
nnoremap <leader><space> :find<space>

set laststatus=2 " always show status line

" tab to space
set expandtab
set smarttab

" highlight search
set incsearch
set hlsearch

set autoindent " indent besed on previous line

set wrap " wrap line

" Check if environment variable PREFIX contains com.termux
let g:is_android = !empty($PREFIX) && $PREFIX =~# 'com\.termux'

if g:is_android
    set clipboard=unnamedplus
else
    set clipboard=unnamed
endif

set nowritebackup

if has('gui_running')
    " disable toolbar
    set guioptions-=T
    " disable menu bar
    set guioptions-=m
    " number of colors
    set t_Co=256
    " tab label
    set guitablabel=%M\ %t
endif

syntax enable

" ignore case when searching
set ignorecase
set smartcase

set lazyredraw
set magic

set timeoutlen=500 " time for key sequence

set wildignore=*.o,*~,*.pyc
if has('win16') || has('win32')
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

" curso sharp
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

set hidden " hidden buffer

set history=500 " command history

set number relativenumber " line number

filetype plugin on
filetype indent on

set updatetime=500

" mouse support
set mouse=a
set smoothscroll

" 24-bit color TUI
set termguicolors

if executable('rg')
    set grepprg=rg\ --vimgrep\ --no-hidden\ --no-heading\
endif

set foldmethod=marker

set shortmess-=S " show she search count

set gdefault " substitute all matches

" auto auto
" au BufLeave,CursorHold,FocusLost * if(getbufinfo('%')[0].changed) | sil do BufWritePre | sil! up | sil do BufWritePost | endif

" Autosession
" au VimEnter * nested if (len(v:argv) == 1) | silent! source Session.vim | endif
" au VimLeave * if (len(v:argv) == 1) | mksession! | endif

" autocmd BufWritePost ~/.local/share/chezmoi/* ! chezmoi apply --source-path "%"

function Chezmoi()
  ! chezmoi apply --source-path "%"
endfunction

command! Chezmoi call Chezmoi()

" set autocomplete
" set complete=o^5,.^5,w^5,b^5,u^5
" set completeopt=popup
"
" inoremap <silent><expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
" inoremap <silent><expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" command completion
autocmd CmdlineChanged [:\/\?] call wildtrigger()
set wildmode=noselect:lastused,full
set wildoptions=pum
autocmd CmdlineEnter [\/\?] set pumheight=8
autocmd CmdlineLeave [\/\?] set pumheight&

if executable('sdcv')
    set keywordprg=sdcv\ -n
endif
"}}}
"{{{ ale config
let g:ale_completion_enabled = 0
let g:ale_set_balloons = 1
let g:ale_hover_to_preview = 1
let g:ale_floating_preview = 1
" set omnifunc=ale#completion#OmniFunc
"}}}

import 'plugins.vim'

"{{{ coc config
let g:coc_node_path = exepath('node')

" coc.nvim
" Use tab for trigger completion with characters ahead and navigate
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list
nmap <silent> [d <Plug>(coc-diagnostic-prev)
nmap <silent> ]d <Plug>(coc-diagnostic-next)

" GoTo code navigation
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

" Use K to show documentation in preview window
nnoremap <silent> K :call ShowDocumentation()<CR>

" Highlight the symbol and its references when holding the cursor
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming
nnoremap <leader>R <plug>(coc-rename)

" Formatting selected code
" xmap <leader>f  <Plug>(coc-format-selected)
" nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s)
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying code actions to the selected code block
" Example: `<leader>aap` for current paragraph
" xmap <leader>a  <Plug>(coc-codeaction-selected)
" nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying code actions at the cursor position
" nmap <leader>ac  <Plug>(coc-codeaction-cursor)
" Remap keys for apply code actions affect whole buffer
" nmap <leader>as  <Plug>(coc-codeaction-source)
" Apply the most preferred quickfix action to fix diagnostic on the current line
" nmap <leader>qf  <Plug>(coc-fix-current)

" Remap keys for applying refactor code actions
" nmap <silent> <leader>re <Plug>(coc-codeaction-refactor)
" xmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)
" nmap <silent> <leader>r  <Plug>(coc-codeaction-refactor-selected)

" Run the Code Lens action on the current line
" nmap <leader>cl  <Plug>(coc-codelens-action)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Remap <C-f> and <C-b> to scroll float windows/popups
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" Use CTRL-S for selections ranges
" Requires 'textDocument/selectionRange' support of language server
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer
command! -nargs=0 Format :call CocActionAsync('format')

" Add `:Fold` command to fold current buffer
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer
command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline
set statusline^=%{coc#status()}%{get(b:,'coc_current_function',''\'''\')}

let g:coc_global_extensions = ['coc-fish', '@yaegassy/coc-marksman', 'coc-emoji', 'coc-dash-complete', 'coc-just-complete', 'coc-translator', 'coc-perl', 'coc-go', 'coc-json', 'coc-prettier', 'coc-basedpyright', 'coc-r-lsp', 'coc-sumneko-lua', 'coc-texlab', 'coc-toml', 'coc-vimlsp', 'coc-yaml', 'coc-pairs', 'coc-snippets', 'coc-marketplace', 'coc-translator' ]
if !has('win32')
    let g:coc_global_extensions += ['coc-sh']
endif

" limit completion item
let g:coc_filetype_map = { 'yaml.ansible': 'ansible', }
set pumheight=10

nmap <Leader>K <Plug>(coc-translator-p)
vmap <Leader>K <Plug>(coc-translator-pv)

" coc snippets
imap <C-j> <Plug>(coc-snippets-expand-jump)
"}}}
"{{{ tokyonight config
" let g:tokyonight_style = 'night' " available: night, storm
" let g:tokyonight_enable_italic = 1
" colorscheme tokyonight
"}}}
"{{{ vim easy align config
" xmap ga <Plug>(EasyAlign)
" nmap ga <Plug>(EasyAlign)
"}}}
"{{{ suda config
" let g:suda_smart_edit = 1
"}}}
"{{{ lightline config
let g:lightline = {
      \ 'colorscheme': 'embark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'zoomed', 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'inactive': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename', 'modified' ] ],
      \   'right': [ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'fileformat', 'fileencoding', 'filetype' ] ]
      \ },
      \ 'component_function': {
      \   'filename': 'LightlineTruncatedFileName',
      \   'zoomed': 'zoom#statusline'
      \ }
      \ }

function! LightlineTruncatedFileName()
let l:filePath = expand('%')
    if winwidth(0) > 100
        return l:filePath
    else
        return pathshorten(l:filePath)
    endif
endfunction
"}}}
"{{{ vim workspace config
let g:workspace_autocreate = 1
let g:workspace_session_disable_on_args = 1
let g:workspace_session_directory = expand('~') . '/.local/share/vim/sessions/'
let g:workspace_autosave = 1
let g:workspace_autosave_always = 1
let g:workspace_autosave_ignore = ['gitcommit', 'suprawater', 'qf']
let g:workspace_undodir = expand('~') . '/.local/share/vim/undo/'
"}}}
"{{{ which key config
nnoremap <silent> <leader> <cmd>WhichKey '<Space>'<CR>
let g:which_key_map = {}
let g:which_key_map['f'] = {
      \ 'name': 'files',
      \ 'f'   : [':Files', 'Files'],
      \ ' '   : [':GFiles', 'Git Files'],
      \ }
let g:which_key_map['w'] = {
      \ 'name': 'windows',
      \ 'w'   : ['<C-W>w'     , 'other-window'],
      \ 'd'   : ['<C-W>c'     , 'delete-window'],
      \ '-'   : ['<C-W>s'     , 'split-window-below'],
      \ '|'   : ['<C-W>v'     , 'split-window-right'],
      \ '2'   : ['<C-W>v'     , 'layout-double-columns'],
      \ 'h'   : ['<C-W>h'     , 'window-left'],
      \ 'j'   : ['<C-W>j'     , 'window-below'],
      \ 'l'   : ['<C-W>l'     , 'window-right'],
      \ 'k'   : ['<C-W>k'     , 'window-up'],
      \ 'H'   : ['<C-W>5<'    , 'expand-window-left'],
      \ 'J'   : [':resize +5' , 'expand-window-below'],
      \ 'L'   : ['<C-W>5>'    , 'expand-window-right'],
      \ 'K'   : [':resize -5' , 'expand-window-up'],
      \ '='   : ['<C-W>='     , 'balance-window'],
      \ 's'   : ['<C-W>s'     , 'split-window-below'],
      \ 'v'   : ['<C-W>v'     , 'split-window-below'],
      \ '?'   : ['Windows'    , 'fzf-window'],
      \ }
call which_key#register('<Space>', "g:which_key_map")
"}}}
"{{{ org config
let g:org_export_emacs = exepath('emacs')
"}}}
"{{{ vim dir config
" nnoremap <bs> <cmd>Dir<cr>
"}}}
"{{{ catppuccin config
" colorscheme catppuccin_mocha
"}}}
"{{{ netrw config
" nnoremap <bs> <cmd>Explore<cr>
"}}}
"{{{ lsp config
" let lspOpts = #{autoHighlightDiags: v:true}
" autocmd User LspSetup call LspOptionsSet(lspOpts)
"
" let lspServers = [#{
" 	\	  name: 'yaml-language-server',
" 	\	  filetype: ['yaml'],
" 	\	  path: exepath('yaml-language-serever')
" 	\	  args: ['--stdio']
" 	\ }]
" autocmd User LspSetup call LspAddServer(lspServers)
"}}}
"{{{ pear tree config
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1
"}}}
"{{{ vim exlporer config
" nnoremap <bs> <cmd>VimExplorer<cr>
"}}}
"{{{ vim dispatch config
nnoremap <leader>cc <cmd>Make<CR>
nnoremap <leader>cC <cmd>Dispatch<CR>
"}}}
"{{{ vim dirvish config
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
command! -nargs=? -complete=dir Explore Dirvish <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish <args>
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>
let g:dirvish_mode = ':sort ,^.*[\/],'
"}}}
"{{{ floaterm config
let g:floaterm_opener = 'edit'
let g:floaterm_height = 0.999
let g:floaterm_width = 0.99
command Lazygit FloatermNew lazygit
command Lf FloatermNew lf
"}}}
"{{{ vim subversive config
nnoremap s <plug>(SubversiveSubstitute)
nnoremap ss <plug>(SubversiveSubstituteLine)
nnoremap S <plug>(SubversiveSubstituteToEndOfLine)
"}}}
"{{{ ultisnips config
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"}}}
"{{{ vim-qf config
nmap <Home> <Plug>(qf_qf_previous)
nmap <End>  <Plug>(qf_qf_next)
nmap <C-Home> <Plug>(qf_loc_previous)
nmap <C-End>  <Plug>(qf_loc_next)
nmap <F5> <Plug>(qf_qf_toggle)
nmap <F6> <Plug>(qf_loc_toggle)
let g:qf_mapping_ack_style = 1
"}}}
"{{{ fugitive config
nmap <leader>gg <cmd>G<cr>
"}}}
"{{{ embark config
colorscheme embark
"}}}
"{{{ onedark config
" colorscheme onedark
"}}}
"{{{ startify config
let g:startify_change_to_vcs_root = 1
let g:startify_session_persistence = 1
let g:startify_enable_special = 0
"}}}
"{{{ signify config
let g:signify_line_highlight = 1
let g:signify_number_highlight = 1
highlight SignifySignAdd    ctermfg=green  guifg=#00ff00 cterm=NONE gui=NONE
highlight SignifySignDelete ctermfg=red    guifg=#ff0000 cterm=NONE gui=NONE
highlight SignifySignChange ctermfg=yellow guifg=#ffff00 cterm=NONE gui=NONE
"}}}
