- name: Update scoop config
  tags: scoop-config
  block:
    - name: Create scoop config folder
      ansible.windows.win_file:
        dest: "{{ ansible_facts.user_dir }}\\.config\\scoop"
        state: directory
    - name: Check scoop config file
      ansible.windows.win_stat:
        path: "{{ ansible_facts.user_dir }}\\.config\\scoop\\config.json"
      register: scoop_config_stat
    - name: Get scoop config content
      ansible.windows.slurp:
        src: "{{ ansible_facts.user_dir }}\\.config\\scoop\\config.json"
      register: scoop_config_content
      when: scoop_config_stat.stat.exists is true
    - name: Set scoop config
      vars:
        config:
          use_lessmsi: true
          aria2-enabled: true
          aria2-warning-enabled: false
          use_sqlite_cache: true
          force_update: true
          use_external_7zip: true
          gh_token: "{{ lookup('gopass', 'github/ourgal/token') | trim }}"
          url_proxy: https://v6.gh-porxy.org
      ansible.windows.win_copy:
        dest: "{{ ansible_facts.user_dir }}\\.config\\scoop\\config.json"
        content: "{{ scoop_config_content.content | b64decode | from_json | combine(config) | to_json }}"
      when: scoop_config_stat.stat.exists is true
    - name: Set scoop config
      vars:
        config:
          use_lessmsi: true
          aria2-enabled: true
          aria2-warning-enabled: false
          use_sqlite_cache: true
          force_update: true
          use_external_7zip: true
          gh_token: "{{ lookup('gopass', 'github/ourgal/token') | trim }}"
          url_proxy: https://v6.gh-porxy.org
      ansible.windows.win_copy:
        dest: "{{ ansible_facts.user_dir }}\\.config\\scoop\\config.json"
        content: "{{ config | to_json }}"
      when: scoop_config_stat.stat.exists is false
- name: Install scoop-proxy-cn
  ansible.windows.win_shell: iwr -useb https://scoop.201704.xyz | iex
  when:
    - windows_install_scoop_is_admin is false
    - windows_install_scoop_proxy_cn is true
- name: Install scoop-proxy-cn
  ansible.windows.win_shell: |
    irm https://scoop.201704.xyz -outfile 'install.ps1'
    .\install.ps1 -RunAsAdmin
    rm .\install.ps1
  when:
    - windows_install_scoop_is_admin is true
    - windows_install_scoop_proxy_cn is true
- name: Install scoop
  ansible.windows.win_shell: iwr -useb https://get.scoop.sh | iex
  when:
    - windows_install_scoop_is_admin is false
    - windows_install_scoop_proxy_cn is false
    - windows_install_scoop_cn is false
- name: Install scoop
  ansible.windows.win_shell: |
    irm https://get.scoop.sh -outfile 'install.ps1'
    .\install.ps1 -RunAsAdmin
    rm .\install.ps1
  when:
    - windows_install_scoop_is_admin is true
    - windows_install_scoop_proxy_cn is false
    - windows_install_scoop_cn is false
- name: Install scoop-cn
  ansible.windows.win_shell: iwr -useb https://v6.gh-proxy.org/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 | iex
  when:
    - windows_install_scoop_is_admin is false
    - windows_install_scoop_cn is true
- name: Install scoop-cn
  ansible.windows.win_shell: |
    irm https://v6.gh-proxy.org/https://raw.githubusercontent.com/duzyn/scoop-cn/master/install.ps1 -outfile 'install.ps1'
    .\install.ps1 -RunAsAdmin
    rm .\install.ps1
  when:
    - windows_install_scoop_is_admin is true
    - windows_install_scoop_cn is true
- name: Install base packages via scoop
  tags: scoop
  community.windows.win_scoop:
    name: "{{ item | basename }}"
    global: false
  register: result
  retries: 3
  delay: 5
  until: result is not failed
  loop:
    - main/lessmsi
    - main/aria2
    - main/7zip
    - main/git
- name: Add scoop buckets
  community.windows.win_scoop_bucket:
    name: "{{ item }}"
    state: present
  loop:
    - extras
    - nerd-fonts
    - nonportable
  when:
    - windows_install_scoop_proxy_cn is false
    - windows_install_scoop_cn is false
- name: Add scoop buckets
  ansible.windows.win_shell: "if (!($(scoop bucket list).name -contains '{{ item }}' )) { scoop bucket add {{ item }} }"
  when: windows_install_scoop_proxy_cn is true
  loop:
    - extras
    - nerd-fonts
    - nonportable
