[my]
name = "zxc"
[my.msys2]
packages = ["mingw-w64-x86_64-aspell"]
[my.font]
monospace = "FiraCode Nerd Font Mono"
[my.git.sign]
ssh = false
gpg = true
[my.termux.note20]
username = "u0_a644"
[my.termux.m6]
username = "u0_a455"
[my.pip]
mirror = "https://mirrors.cernet.edu.cn/pypi/web/simple/"
[my.modules]
mpd = false
navidrome = true

mcfly = true
atuin = false
