[my.msys2]
packages = ["fish", "nnn", "atool", "libarchive", "tmux", "zsh"]

[my.font]
monospace = "IosevkaTerm NFM"
sans = "Noto Sans CJK SC"

[my.git.sign]
ssh = false
gpg = true

[my.git.user]
name = "fairever"
email = "git@fairever.aleeas.com"

[my.shell]
windows = "pwsh"

[my.terminal]
windows = "wt"

[my.pip]
mirror = "https://mirrors.nju.edu.cn/pypi/web/simple/"

[my.sbsrf]
url="https://github.com/sbsrf/sbsrf/releases/download/20260425/sbsrf.zip"

[my.alist.local]
host = "http://localhost:5244"

[my.dufs.bucket]
host = "http://localhost:5000"

[my.doomemacs]
commit = "d8d75443d39d95f3c5256504eb838e0acc62ef44"
elfeed_protocol = true
elfeed_org = false
elfeed_youtube = false

[my.browser]
default = "firefox"

[my.ssh]
known_hosts = [
    "home.local,192.168.123.100 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOKREEGtjhZmTsIruPjBmBp0fPHKxfUSbUilpIzVMoBF",
    "[brix.local]:23231 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqhuTozhEUlnOCkH1LXw55IUaZHzcO4IKmr1uPOT41u",
    "[192.168.123.206]:23231 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqhuTozhEUlnOCkH1LXw55IUaZHzcO4IKmr1uPOT41u",
    "brix.local,192.168.123.206 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJADK7A2hbOUUfvCxe2xNhkVpEHIy3CKK0+bkTE5Uqur",
    "surface.local ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHVX0quUeLWv/vQZ528bsWAqYB+uaVC5o/SMmgtnjPkD",
    "[192.168.1.103]:23231 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+SAtnk+RxrEzSgeZU7MyFAubqR0Mp5wnu5YvH5mpqn",
    "[192.168.123.191]:23231 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+SAtnk+RxrEzSgeZU7MyFAubqR0Mp5wnu5YvH5mpqn",
    "[localhost]:8022 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+SAtnk+RxrEzSgeZU7MyFAubqR0Mp5wnu5YvH5mpqn",
    "[localhost]:8023 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM+qtBP8Hw2P2GiZ8UWOFQ6ca/INlOsRxDwVl1U7Th4Kddl2gXkwrJMWgZMBlX0ynoeSN6eN/1fAamufbMgcZbs=",
    "[ssh.github.com]:443 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl",
    "[ssh.github.com]:443 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=",
    "[ssh.github.com]:443 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
]

[my.modules]

[my.modules.windows.startup]
glazewm.enable = false
deskflow_client.enable = false
deskflow_server.enable = false
aria2.enable = true
transmission.enable = true
espanso.enable = true
alist.enable = true
mpd.enable = true
gpg_agent.enable = true
kde_connect.enable = true
wezterm.enable = false
firefox.enable = false
brave.enable = true
chromium.enable = false
vscode.enable = false
vscodium.enable = false
leo.enable = false
everything.enable = true
autohotkey.enable = false
powertoys.enable = false
dufs.enable = true
copyparty.enable = true
altrun.enable = false
navidrome.enable = false
jellyfin_mpv_shim.enable = false
emacs.enable = false
emacs_daemon.enable = false
wt.enable = true
syncthing.enable = true
torrserver.enable = false
flameshot.enable = true
seanime.enable = true
rclone.enable = false
gotify.enable = false

[my.modules.shell.pwsh]
starship.enable = true
oh_my_posh.enable = false
sfsu.enable = false
zoxide.enable = true
atuin.enable = true
mcfly.enable = false
navi.enable = true

[my.modules.shell.clink]
starship.enable = true
oh_my_posh.enable = false
zoxide.enable = true

[my.modules.shell.bash]
ble_sh.enable = true
fzf.enable = true
starship.enable = true
oh_my_posh.enable = false
atuin.enable = false
mcfly.enable = true
zoxide.enable = true
pay_respects.enable = true

[my.modules.shell.fish]
oh_my_posh.enable = false
starship.enable = true
fzf.enable = true
mcfly.enable = false
atuin.enable = true
navi.enable = true
carapace.enable = true
zoxide.enable = true

[my.modules.mpv.plugins]
uosc = true
smartskip = true
thumbfast = true
manga_reader = true
M_x = true
leader = true
sponsorblock_chapterized = true
quality_menu = true
torrserver_hook = true
ytdlautoformat = false
clipshot = true
file_browser = true
anilist_updater = true
smart_copy_paste = true
betterchapters = true
costum = false
autocrop = true

[my.modules.firefox]
theme = "flexfox"

[my.modules.nuc.windows.windows.startup]
deskflow_client.enable = true

[my.modules.bed.windows.windows.startup]
jellyfin_mpv_shim.enable = true

[my.modules.work.windows.windows.startup]
deskflow_server.enable = true
gotify.enable = true

[my.modules.surface.void]

[my.modules.surface.void.mpv.plugins]
anilist_updater = false

[my.modules.localhost.android]
