[my.termux.packages]
install = [
  # AI
  "aichat",
  # anime
  "ani-cli",
  # book
  "bk",
  # chat
  "weechat",
  # dev
  "direnv",
  "editorconfig-core-c-static",
  "editorconfig-core-c",
  "just",
  "make",
  "termux-apt-repo",
  "termux-create-package",
  "wakatime-cli",
  # sqlite
  "sqlite",
  # nodejs
  "nodejs-lts",
  # rust
  "rust",
  # markdown
  "marksman",
  # json
  "jq",
  # go
  "golang",
  # haskell
  "ghc",
  # toml
  "taplo",
  # latex
  "tectonic",
  "texlab",
  "texlive-bin",
  # python
  "python",
  # document
  "pandoc",
  "texinfo",
  # download
  "aria2",
  "axel",
  "cloneit",
  "python-yt-dlp",
  "transmission",
  # database
  "recutils",
  # editor
  "helix",
  "helix-grammars",
  "neovim",
  "python-pynvim",
  "vim",
  "kakoune",
  "kakoune-lsp",
  "emacs",
  # encrypt
  "gopass",
  # image
  "gnuplot",
  # image edit
  "imagemagick",
  # math
  "qalc",
  # ascii art
  "figlet",
  "toilet",
  # dotfiles
  "chezmoi",
  # file manage
  "lf",
  "clifm",
  "nnn",
  "ranger",
  "vifm",
  "yazi",
  "mc",
  # git
  "gh",
  "git",
  # git stats
  "onefetch",
  # git tui
  "gitui",
  "lazygit",
  "tig",
  # git diff
  "diff-so-fancy",
  "git-delta",
  # git encrypt
  "git-crypt",
  # git script
  "git-extras",
  # git lfs
  "git-lfs",
  # translation
  "translate-shell",
  # typing
  "ttyper",
  # share
  "croc",
  "dufs",
  "miniserve",
  "rclone",
  "ttyd",
  # shell
  "fish",
  # which
  "which",
  # screen
  "tmux",
  "zellij",
  # cd
  "zoxide",
  # man
  "tealdeer",
  # prompt
  "starship",
  "oh-my-posh",
  # cp
  "rsync",
  # rename
  "rnr",
  # snippets
  "navi",
  "pet",
  # grep
  "ripgrep",
  # fuzzy
  "broot",
  "fzf",
  # completion
  "carapace",
  # history
  "atuin",
  "mcfly",
  # paper
  "bat",
  "moor",
  # utils
  "moreutils",
  # system
  "termux-api",
  # package manager
  "oma",
  "nala",
  # network
  "iproute2",
  # ping
  "gping",
  # font
  "fontconfig-utils",
  # dns
  "doge",
  "q-dns-client",
  # ls
  "eza",
  "tree",
  # stats
  "fastfetch",
  "cpufetch",
  # top
  "htop",
  # find
  "fd",
  # du
  "diskus",
  "dua",
  "duc",
  "dust",
  "gdu",
  # df
  "duf",
  # archive
  "atool",
  "unrar",
  # services
  "termux-services",
  # ssh
  "openssh",
  # rss
  "newsboat",
  # video edit
  "ffmpeg",
]
uninstall = []

[my.termux.pip.packages]
install = ["pipx"]

[my.termux.pipx.packages]
install = ["copyparty", "mdformat", "advance-touch", "aria2p[tui]"]

[my.scoop]
offical = false
scoop_proxy_cn = true

[my.scoop.packages]
install = [
  # AI
  "aichat",
  # android
  "adb",
  "scrcpy",
  # audio
  "navidrome",
  "cliamp",
  # CMS
  "hugo",
  "cobalt",
  # dev
  "chsrc",
  "dprint",
  "wakatime-cli",
  "cloc",
  # bash
  "shellcheck",
  "shfmt",
  # c
  "clangd",
  # csharp
  "bflat",
  # compile
  "make",
  # environment
  "task",
  "cmake",
  "msys2",
  "direnv",
  "tree-sitter",
  "dirhash",
  # haskell
  "haskell",
  "haskell-cabal",
  "haskell-language-server",
  "stack",
  # go
  "go",
  # json
  "jq",
  # latex
  "texlab",
  "tectonic",
  # lua
  "lua-language-server",
  "stylua",
  # markdown
  "autocorrect",
  "marksman",
  # nodejs
  "yarn",
  "pnpm",
  # perl
  "perl",
  # powershell
  "powershelleditorservices",
  # python
  "ruff",
  "ty",
  "uv",
  # rust
  "rust",
  "cargo-binstall",
  # sql
  "sqlite",
  # toml
  "taplo",
  "tombi",
  # web
  "static-web-server",
  # yaml
  "yamlfmt",
  # disk
  "smartmontools",
  "dd",
  # document
  "pandoc",
  "cht",
  # dotfile_manager
  "chezmoi",
  # downloader
  "gallery-dl",
  "yt-dlp",
  "pget",
  "wget2",
  "wget",
  "aria2",
  # editor
  "vim",
  "helix",
  "neovim",
  "fresh",
  # email
  "mailsend",
  # encrypt
  "gpg",
  "openssl",
  "gopass",
  "gopass-jsonapi",
  "sops",
  # file_manager
  "lf",
  "yazi",
  "superfile",
  # fuzzy_finder
  "broot",
  "fzf",
  # git
  "jj",
  # git_auto
  "gitomatic",
  # git_bug
  "git-bug",
  # git_github
  "gh",
  # git_push
  "mob",
  "legit",
  # git_lfs
  "git-lfs",
  # git_fixup
  "git-absorb",
  # git_diff
  "diff-so-fancy",
  "delta",
  "difftastic",
  # git_encrypt
  "git-crypt",
  # git_tui
  "gitui",
  # git_gui
  "git-cola",
  # git_server
  "gogs",
  # git_search
  "gitql",
  # git_hook
  "lefthook",
  # image
  "gnuplot",
  # image_info
  "exiftool",
  # image_edit
  "imagemagick",
  # network
  "dog",
  "nali",
  "nmap",
  "q-dns",
  "tcping",
  # proxy
  "connect",
  # scoop_helper
  "scoop-search",
  # search
  "everything-cli",
  # remote
  "termscp",
  "ttyd",
  # qr_code
  "qr",
  "qrcp",
  # share
  "croc",
  "dufs",
  "miniserve",
  "portal",
  "rclone",
  "syncthing",
  "alist",
  "serve",
  "simple-http-server",
  "git-annex",
  # shell
  "clink",
  "clink-completions",
  "cmder-full",
  "pwsh",
  "nu",
  "yori",
  # ascii_art
  "rainbow",
  # cd
  "zoxide",
  # df
  "duf",
  # du
  "dua",
  "dust",
  # find
  "fd",
  # grep
  "grep",
  "ripgrep",
  "gawk",
  "igrep",
  # history
  "mcfly",
  "atuin",
  # less
  "bat",
  "less",
  # ls
  "eza",
  # man
  "tealdeer",
  # prompt
  "starship",
  "oh-my-posh",
  # rename
  "rnr",
  # sed
  "sd",
  "sed",
  # shasum
  "shasum",
  # snippets
  "navi",
  # system_info
  "fastfetch",
  "ntop",
  "btop",
  "bottom",
  "cpufetch",
  # tmux
  "psmux",
  "zellij",
  # typing
  "ttyper",
  # unrar
  "unrar",
  "unzip",
  # utils
  "coreutils",
  "nircmd",
  # mv
  "brename",
  # which
  "which",
  # system
  "dos2unix",
  "goodbyedpi",
  "file",
  "cyme",
  # archive
  "zip",
  "bzip2",
  # unpack
  "innounp",
  "gzip",
  "innoextract",
  "xz",
  # sudo
  "gsudo",
  # service
  "nssm",
  # package_manager
  "pipx",
  "winget",
  "topgrade",
  "meta-package-manager",
  # clipboard
  "clipboard@0.9.0.1",
  # notification
  "noti",
  "gotify-server",
  "gotify-cli",
  # ps
  "witr",
  # rm
  "trashy",
  # text_expander
  "espanso",
  # video_editor
  "ffmpeg",
  "butterflow",
  # nerd fonts
  "JetBrainsMono-NF"
]

install_without_proxy = [
  # audio
  "mpd",
  # dev
  "editorconfig",
  "aspell",
  "diffutils",
  # CA
  "cacert",
  # binary
  "binutils",
  # csharp
  "scriptcs",
]
